// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t * ui_HomeScreen;
void ui_event_LimbControl1(lv_event_t * e);
lv_obj_t * ui_LimbControl1;
lv_obj_t * ui_Label1;
// CUSTOM VARIABLES
lv_obj_t * uic_HomeScreen;
lv_obj_t * uic_LimbControl;


// SCREEN: ui_LCScreen
void ui_LCScreen_screen_init(void);
lv_obj_t * ui_LCScreen;
lv_obj_t * ui_FrontLeft;
lv_obj_t * ui_FLLabel;
lv_obj_t * ui_Side;
void ui_event_FLSaddB(lv_event_t * e);
lv_obj_t * ui_FLSaddB;
lv_obj_t * ui_Label2;
void ui_event_FLSsubB(lv_event_t * e);
lv_obj_t * ui_FLSsubB;
lv_obj_t * ui_Side2;
lv_obj_t * ui_Side1;
void ui_event_FLTaddB(lv_event_t * e);
lv_obj_t * ui_FLTaddB;
lv_obj_t * ui_Label4;
void ui_event_FLTsubB(lv_event_t * e);
lv_obj_t * ui_FLTsubB;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Side3;
void ui_event_FLBaddB(lv_event_t * e);
lv_obj_t * ui_FLBaddB;
lv_obj_t * ui_Label3;
void ui_event_FLBsubB(lv_event_t * e);
lv_obj_t * ui_FLBsubB;
lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
lv_obj_t * uic_LCScreen;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_LimbControl1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LCScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_LCScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        getPositionLegs(e);
    }
}

void ui_event_FLSaddB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FLSadd(e);
    }else if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        FLSadd(e);
    }
}

void ui_event_FLSsubB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FLSsub(e);
    }else if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        FLSsub(e);
    }
}

void ui_event_FLTaddB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FLTadd(e);
    }else if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        FLTadd(e);
    }
}

void ui_event_FLTsubB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FLTsub(e);
    }else if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        FLTsub(e);
    }
}

void ui_event_FLBaddB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FLBadd(e);
    }else if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        FLBadd(e);
    }
}

void ui_event_FLBsubB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FLBsub(e);
    }else if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        FLBsub(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomeScreen_screen_init();
    ui_LCScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomeScreen);
}
