// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t * ui_HomeScreen;
void ui_event_LimbControl1(lv_event_t * e);
extern lv_obj_t * ui_LimbControl1;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_HomeScreen;
extern lv_obj_t * uic_LimbControl;

// SCREEN: ui_LCScreen
void ui_LCScreen_screen_init(void);
extern lv_obj_t * ui_LCScreen;
extern lv_obj_t * ui_FrontLeft;
extern lv_obj_t * ui_FLLabel;
extern lv_obj_t * ui_Side;
void ui_event_FLSaddB(lv_event_t * e);
extern lv_obj_t * ui_FLSaddB;
extern lv_obj_t * ui_Label2;
void ui_event_FLSsubB(lv_event_t * e);
extern lv_obj_t * ui_FLSsubB;
extern lv_obj_t * ui_Side2;
extern lv_obj_t * ui_Side1;
void ui_event_FLTaddB(lv_event_t * e);
extern lv_obj_t * ui_FLTaddB;
extern lv_obj_t * ui_Label4;
void ui_event_FLTsubB(lv_event_t * e);
extern lv_obj_t * ui_FLTsubB;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Side3;
void ui_event_FLBaddB(lv_event_t * e);
extern lv_obj_t * ui_FLBaddB;
extern lv_obj_t * ui_Label3;
void ui_event_FLBsubB(lv_event_t * e);
extern lv_obj_t * ui_FLBsubB;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_LCScreen;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
