// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


void FLSadd(lv_event_t * e)
{

}

void FLSsub(lv_event_t * e)
{
	// Your code here
}

void FLTadd(lv_event_t * e)
{
	// Your code here
}

void FLTsub(lv_event_t * e)
{
	// Your code here
}

void FLBadd(lv_event_t * e)
{
	// Your code here
}

void FLBsub(lv_event_t * e)
{
	// Your code here
}
