// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void getPositionLegs(lv_event_t * e);
void FLSadd(lv_event_t * e);
void FLSsub(lv_event_t * e);
void FLTadd(lv_event_t * e);
void FLTsub(lv_event_t * e);
void FLBadd(lv_event_t * e);
void FLBsub(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
