// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_LCScreen_screen_init(void)
{
    ui_LCScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LCScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FrontLeft = lv_obj_create(ui_LCScreen);
    lv_obj_set_width(ui_FrontLeft, 240);
    lv_obj_set_height(ui_FrontLeft, 160);
    lv_obj_clear_flag(ui_FrontLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FLLabel = lv_label_create(ui_FrontLeft);
    lv_obj_set_width(ui_FLLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FLLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_FLLabel, "Front Left");

    ui_Side = lv_label_create(ui_FrontLeft);
    lv_obj_set_width(ui_Side, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Side, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Side, 0);
    lv_obj_set_y(ui_Side, 30);
    lv_label_set_text(ui_Side, "Side");
    lv_obj_set_style_text_font(ui_Side, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FLSaddB = lv_btn_create(ui_FrontLeft);
    lv_obj_set_width(ui_FLSaddB, 60);
    lv_obj_set_height(ui_FLSaddB, 20);
    lv_obj_set_x(ui_FLSaddB, 70);
    lv_obj_set_y(ui_FLSaddB, 30);
    lv_obj_add_flag(ui_FLSaddB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FLSaddB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_FLSaddB);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "+");

    ui_FLSsubB = lv_btn_create(ui_FrontLeft);
    lv_obj_set_width(ui_FLSsubB, 60);
    lv_obj_set_height(ui_FLSsubB, 20);
    lv_obj_set_x(ui_FLSsubB, 140);
    lv_obj_set_y(ui_FLSsubB, 30);
    lv_obj_add_flag(ui_FLSsubB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FLSsubB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Side2 = lv_label_create(ui_FLSsubB);
    lv_obj_set_width(ui_Side2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Side2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Side2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Side2, "-");

    ui_Side1 = lv_label_create(ui_FrontLeft);
    lv_obj_set_width(ui_Side1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Side1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Side1, 0);
    lv_obj_set_y(ui_Side1, 60);
    lv_label_set_text(ui_Side1, "Top");
    lv_obj_set_style_text_font(ui_Side1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FLTaddB = lv_btn_create(ui_FrontLeft);
    lv_obj_set_width(ui_FLTaddB, 60);
    lv_obj_set_height(ui_FLTaddB, 20);
    lv_obj_set_x(ui_FLTaddB, 70);
    lv_obj_set_y(ui_FLTaddB, 60);
    lv_obj_add_flag(ui_FLTaddB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FLTaddB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_FLTaddB);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "+");

    ui_FLTsubB = lv_btn_create(ui_FrontLeft);
    lv_obj_set_width(ui_FLTsubB, 60);
    lv_obj_set_height(ui_FLTsubB, 20);
    lv_obj_set_x(ui_FLTsubB, 140);
    lv_obj_set_y(ui_FLTsubB, 60);
    lv_obj_add_flag(ui_FLTsubB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FLTsubB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_FLTsubB);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "-");

    ui_Side3 = lv_label_create(ui_FrontLeft);
    lv_obj_set_width(ui_Side3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Side3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Side3, 0);
    lv_obj_set_y(ui_Side3, 90);
    lv_label_set_text(ui_Side3, "Bottom");
    lv_obj_set_style_text_font(ui_Side3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FLBaddB = lv_btn_create(ui_FrontLeft);
    lv_obj_set_width(ui_FLBaddB, 60);
    lv_obj_set_height(ui_FLBaddB, 20);
    lv_obj_set_x(ui_FLBaddB, 70);
    lv_obj_set_y(ui_FLBaddB, 90);
    lv_obj_add_flag(ui_FLBaddB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FLBaddB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_FLBaddB);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "+");

    ui_FLBsubB = lv_btn_create(ui_FrontLeft);
    lv_obj_set_width(ui_FLBsubB, 60);
    lv_obj_set_height(ui_FLBsubB, 20);
    lv_obj_set_x(ui_FLBsubB, 140);
    lv_obj_set_y(ui_FLBsubB, 90);
    lv_obj_add_flag(ui_FLBsubB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FLBsubB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_FLBsubB);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "-");

    lv_obj_add_event_cb(ui_FLSaddB, ui_event_FLSaddB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FLSsubB, ui_event_FLSsubB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FLTaddB, ui_event_FLTaddB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FLTsubB, ui_event_FLTsubB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FLBaddB, ui_event_FLBaddB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FLBsubB, ui_event_FLBsubB, LV_EVENT_ALL, NULL);
    uic_LCScreen = ui_LCScreen;

}
